development:
  sessions:
    default:
      database: local_store_mode_sample_dev
      hosts:
        - 192.168.1.2:27017
test:
  sessions:
    default:
      database: local_store_mode_sample_test
      hosts:
        - 192.168.1.2:27017
